# Generated by Django 5.2.5 on 2025-08-29 18:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuit_Journey', '0007_alter_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fvid',
            field=models.FileField(blank=True, null=True, upload_to='media/static/vids'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='media/static/imgs/'),
        ),
    ]
