# Generated by Django 5.2.5 on 2025-09-02 00:17

# import Circuit_Journey.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuit_Journey', '0009_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fvid',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
