# Generated by Django 5.2.5 on 2025-09-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuit_Journey', '0010_alter_blog_fvid_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fvid',
            field=models.URLField(blank=True, null=True),
        ),
    ]
