# Generated by Django 5.2.5 on 2025-09-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuit_Journey', '0011_alter_blog_fvid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fvid',
            field=models.FileField(blank=True, null=True, upload_to='static/vids'),
        ),
    ]
