# Generated by Django 5.2.5 on 2025-09-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuit_Journey', '0012_alter_blog_fvid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='fvid',
        ),
        migrations.AddField(
            model_name='blog',
            name='video_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
