# Generated by Django 5.2.5 on 2025-09-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuit_Journey', '0013_remove_blog_fvid_blog_video_file_path_blog_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='video_file_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
