# Generated by Django 5.2.5 on 2025-09-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuit_Journey', '0014_remove_blog_video_url_blog_video_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video_file_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video_file_path',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
