# Generated by Django 5.2.5 on 2025-09-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuit_Journey', '0015_alter_blog_video_file_id_alter_blog_video_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video_file_id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='video_file_path',
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%y'),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
