# Generated by Django 5.2.5 on 2025-09-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Circuit_Journey', '0017_alter_blog_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video_name',
        ),
    ]
